### PR TITLE
Feature filter by

### PR DESCRIPTION
**Pull request by meganrm**
@mikelmaron I'm pretty sure this is working but there is only one event with an 'labor' and no events with 'faith'. Is that expected?

### CODE REVIEW

**Comment by mikelmaron** [comment]
@meganrm what options do you see for placement of the filter feature? presently on my screen it overlaps the map. perhaps to the right of the search box, with options within a single line?

Screen Shot 2020-03-07 at 10 17 15 AM

There's presently only one test event with `host_type: faith`. The filter logic isn't working right. If I filter by "Faith Events", all are cleared. If when page loads, I filter by "Labor Events", this one event is visible; if I think filter by "Faith Events", it's still visible. If I switch days, the event disappears.

Also if a pop up is enabled when I filter, the popup remains (it should be closed).

**Comment by mikelmaron** [comment]
The pop up remains if you switch day as well. Any time there's a change like that, popup should be closed.

**Comment by meganrm** [comment]
Yeah I noticed that earlier and forgot to mention it. For the filter placement I was trying to go a bit with the mockup we got, but i can make it one line too

**Comment by meganrm** [comment]
Here are the filters working: two issues I see, the geolocate search includes all addresses, I think we should filter to US. 
I was never able to figure out a callback for the geolocate search. I wanted to hide the insets on search, but wasnt able to figure that out from the docs. Any help?
Mar-07-2020 12-27-37

**Comment by mikelmaron** [comment]
Good call on limiting geocoding to the US. add `countries: 'us'` to initialization of MapboxGeocoder. 

For the callback, you can add that like

    map.addControl(
        new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            mapboxgl: mapboxgl,
            countries: 'us'
        })
            .on('result', function(result) {
              // callback
            }),
        'top-left'
    );

However I was wondering about the zoom/insets behavior. What if the insets were always hidden below a certain zoom level? And add in a America button to the zoom control, similar to Indivisible?

**Comment by mikelmaron** [comment]
@meganrm the issue now with the popups is that it's impossible to click them, because they disappear when moving the mouse. Could this work by keeping the popup visible after mousemove, but hiding the popup if there's any kind of interaction with the map or interface?

**Comment by mikelmaron** [comment]
Also forgot to say, the filter looks good!

**Comment by meganrm** [comment]
I fixed the issue with the popups closing. 

Insets now go away if you search, or click on the map. 

I also added a reset if you clear the search box.

**Comment by mikelmaron** [comment]
Thanks @meganrm merging

**Pull request merged**
